# Generated by Django 3.2.7 on 2021-09-27 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_time', models.DateField()),
                ('event', models.CharField(choices=[('START', 'START'), ('STOP', 'STOP'), ('REPORT', 'REPORT')], max_length=20)),
                ('message', models.CharField(max_length=250)),
                ('actual_time', models.DateField(default=django.utils.timezone.now)),
                ('display_message', models.CharField(max_length=250)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
    ]
